package com.sakshi.sra.smartresearchassistant.service;

import com.sakshi.sra.smartresearchassistant.dto.DocumentCreateRequest;
import com.sakshi.sra.smartresearchassistant.entity.Document;
import com.sakshi.sra.smartresearchassistant.exception.NotFoundException;
import com.sakshi.sra.smartresearchassistant.repository.DocumentRepository;
import org.springframework.stereotype.Service;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

@Service
public class DocumentService {

    private final DocumentRepository repo;

    public DocumentService(DocumentRepository repo) {
        this.repo = repo;
    }

    public Document create(DocumentCreateRequest req) {
        Document doc = new Document(
                null, // id generated by DB/Hibernate
                req.getTitle(),
                req.getAuthor(),
                req.getSourceUrl(),
                req.getNote(),
                OffsetDateTime.now()
        );
        return repo.save(doc);
    }

    public List<Document> findAll() {
        return repo.findAll();
    }

    public Document findById(UUID id) {
        return repo.findById(id).orElseThrow(() ->
                new NotFoundException("Document not found: " + id));
    }

    public void delete(UUID id) {
        if (!repo.existsById(id)) {
            throw new NotFoundException("Document not found: " + id);
        }
        repo.deleteById(id);
    }
}
